language: python
dist: trusty
sudo: true
python:
    - 3.4
    - 3.5
    - 3.6
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libicu-dev build-essential
install:
    - pip install -r requirements.txt
    - pip install .
script:
    - kbdgen -h
