jobs:
  - job: "linux"
    pool:
      vmImage: "ubuntu-18.04"
    steps:
      - script: |
          set -e
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          sudo apt install -y musl musl-tools
          rustup target install x86_64-unknown-linux-musl
          cargo install pyoxidizer
          # git clone https://github.com/divvun/divvun-ci-config.git
        displayName: "Install prerequisites"
      - script: |
          set -e
          source $HOME/.cargo/env
          cargo build --release --target x86_64-unknown-linux-musl
          cp target/x86_64-unknown-linux-musl/release/kbdgen .
          strip ./kbdgen
        displayName: "Build"
      - task: PublishPipelineArtifact@0
        inputs:
          targetPath: "$(System.DefaultWorkingDirectory)/kbdgen"
          artifactName: linux
        displayName: "Publish artifact"

  - job: "macOS"
    pool:
      vmImage: "macOS-10.14"
    steps:
      - script: |
          set -e
          brew uninstall --ignore-dependencies libyaml
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env
          cargo install pyoxidizer 
          # git clone https://github.com/divvun/divvun-ci-config.git
        displayName: "Install prerequisites"
      - script: |
          set -e
          source $HOME/.cargo/env
          cargo build --release
          cp target/release/kbdgen .
          strip ./kbdgen
        displayName: "Build"
      - task: PublishPipelineArtifact@0
        inputs:
          targetPath: "$(System.DefaultWorkingDirectory)/kbdgen"
          artifactName: macos
        displayName: "Publish artifact"
  - job: "Windows"
    pool:
      vmImage: "windows-2019"
    steps:
      - script: |
          PATH=%PATH%;%USERPROFILE%\.cargo\bin
          curl -sLo rustup-init.exe https://win.rustup.rs/
          ./rustup-init.exe -y --default-host=x86_64-pc-windows-msvc --default-toolchain=nightly-x86_64-pc-windows-msvc
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cargo install pyoxidizer
        displayName: "Install prerequisites"
      - script: |
          PATH=%PATH%;%USERPROFILE%\.cargo\bin
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          rustup default nightly-x86_64-pc-windows-msvc
          cargo build --release
          cp target\release\kbdgen.exe .
        displayName: "Build"
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: "$(System.DefaultWorkingDirectory)/kbdgen.exe"
          artifactName: windows
