[package]
name = "kbdgen"
version = "2.0.0-alpha.0"
authors = [
    "Brendan Molloy <brendan@bbqsrc.net>",
    "Pascal Hertleif <pascal@technocreatives.com>"
]
edition = "2018"
license = "Apache-2.0 OR MIT"

[dependencies]
pyembed = { path = "pyembed" }
py-language-tags = { path = "py-language-tags" }
py-logger = { path = "py-logger" }

serde = { version = "1.0.103", features = ["derive"] }
serde_yaml = { version = "0.8.9", git = "https://github.com/killercup/serde-yaml/", branch = "feature/multiline-strings" }
strum = "0.16.0"
strum_macros = "0.16.0"
log = "0.4.8"
snafu = "0.6.0"
unic-ucd-category = "0.9.0"
lazy_static = "1.4.0"
regex = "1.3.1"
unic-segment = "0.9.0"
shrinkwraprs = "0.2.3"
xml-rs = "0.8.0"
jemallocator-global = { version = "0.3", optional = true }
structopt = "0.3.5"
env_logger = "0.7.1"

[dev-dependencies]
pretty_env_logger = "0.3.1"
proptest = "0.9.4"

[features]
default = []
jemalloc = ["jemallocator-global", "pyembed/jemalloc"]

[profile.release]
debug = true

[workspace]
members = [
    ".",
    "kbdgen-cli",
    "py-language-tags",
    "py-logger",
]
