[package]
name = "kbdgen"
version = "0.1.0"
authors = ["Pascal Hertleif <pascal@technocreatives.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
serde = { version = "1.0.94", features = ["derive"] }
serde_yaml = "0.8.9"
strum = "0.15.0"
strum_macros = "0.15.0"
log = "0.4.6"
snafu = "0.4.1"

[dev-dependencies]
pretty_env_logger = "0.3.0"

[profile.release]
debug = true
