internalName: sami_keyboard

locales:
  en:
    name: "Brendan's Sami Keyboard"
    description: "A test keyboard for Northern and Kildin Sami."
  nb:
    name: "Samisk Tastatur"
    description: "Et testtastatur for nordsamisk og kildinsamisk."

author: Brendan Molloy
email: brendan@bbqsrc.net

layouts: [sme, sjd]

targets:
  android:
    packageId: so.brendan.keyboards.sami
    keyStore: /Users/brendan/git/softkbdgen/test.keystore
    keyAlias: sami_keyboard

  ios:
    packageId: so.brendan.keyboards.sami

